### ISSUE TITLE
Implement vendor collection

### ISSUE THREAD

**Issue by christopherjaro** [tasteofmanoa/manoa-munchies#11]
- Work done on this issue must be done in a branch labeled m3-vendb-(initials). 
    - Name
    - Description
    - Open hours Days and time 
    - Tastes (array)
    - Picture (should be in the form of a URL)
    - Cover picture: (should be in the form of a URL)
    - Average Rating: function that pulls from reviews
    - reviews: type string
    - favorites: type: number some sort of function?

**Comment by richardkahakui** [comment]
review: array of strings
     pulls from a list of user names
     made similar to results pulls

**Comment by christopherjaro** [comment]
brandon fixed the search vendor population issue
