### ISSUE TITLE
Vendor profile page mockup

### ISSUE THREAD

**Issue by christopherjaro** [tasteofmanoa/manoa-munchies#20]
- Work done in this branch to be done in m2-venpromock-intials
- Similar to user profile. There should be a menu section with elements of a typical menu.
- Should have a gear icon on the profile (exclusive to that vendor).

**Comment by brandondoan** [comment]
Sorry! Let me know what else you want me to change or add.

**Comment by christopherjaro** [comment]
Finished edits to vendor profile page, changed some images around on landing pages.
