### ISSUE TITLE
Mockup Food Vendor Directory

### ISSUE THREAD

**Issue by christopherjaro** [tasteofmanoa/manoa-munchies#8]
- Do work for this issue in a branch called "issue-8" append first initial of name. (e.g. if your name is Darth Vader, the branch name should be "issue-8d")
- Should be relatively similar to that of find friends directory 
- Cards in this directory should have the following elements/info
    - Name
    - Picture
    - Description 
    - Rating (include stars)

**Comment by brandondoan** [comment]
Mostly done, need to improve the look of the filter and add ratings instead of likes

**Comment by christopherjaro** [comment]
Made revisions to header, footer, homepage, search, profile page, and vendor directory search. Changes done can be seen in m2-editmock-cpj.
